---
name: Build and Release .deb Package
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build-deb:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Get Version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build cyclonedx-cr Binary
        run: |
          docker run --rm --platform linux/${{ matrix.arch }} -v $(pwd):/cyclonedx-cr -w /cyclonedx-cr --entrypoint="" 84codes/crystal:latest-debian-12 sh -c "
            apt-get update && apt-get install -y --no-install-recommends build-essential pkg-config libyaml-dev libxml2-dev liblzma-dev zlib1g-dev libpcre2-dev libgc-dev ca-certificates git curl &&
            shards install --production &&
            /usr/bin/crystal build src/main.cr -o cyclonedx-cr --release --no-debug
          "
      - name: Create Debian Package Structure
        run: |
          mkdir -p cyclonedx-cr_${{ env.VERSION }}_${{ matrix.arch }}/DEBIAN
          mkdir -p cyclonedx-cr_${{ env.VERSION }}_${{ matrix.arch }}/usr/bin
          mkdir -p cyclonedx-cr_${{ env.VERSION }}_${{ matrix.arch }}/usr/share/doc/cyclonedx-cr
          cp cyclonedx-cr cyclonedx-cr_${{ env.VERSION }}_${{ matrix.arch }}/usr/bin/
          cp README.md cyclonedx-cr_${{ env.VERSION }}_${{ matrix.arch }}/usr/share/doc/cyclonedx-cr/
          cp LICENSE cyclonedx-cr_${{ env.VERSION }}_${{ matrix.arch }}/usr/share/doc/cyclonedx-cr/
      - name: Create DEBIAN/control file
        run: |
          cat > cyclonedx-cr_${{ env.VERSION }}_${{ matrix.arch }}/DEBIAN/control << EOF
          Package: cyclonedx-cr
          Version: ${{ env.VERSION }}
          Architecture: ${{ matrix.arch }}
          maintainer: HAHWUL <hahwul@gmail.com>, KSG <ksg97031@gmail.com>
          Description: Attack surface detector that identifies endpoints by static analysis
          Depends: libc6 (>= 2.17)
          EOF
      - name: Build .deb Package
        run: |
          dpkg-deb --build cyclonedx-cr_${{ env.VERSION }}_${{ matrix.arch }}
      - name: Upload .deb to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cyclonedx-cr_${{ env.VERSION }}_${{ matrix.arch }}.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
